feriacultiva/apps/publicaciones/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "publicacion"

urlpatterns = [

    path('', views.ListarPublicaciones.as_view(), name="listarPublicaciones"),

    path('GestionPublicaciones', views.ListarPublicacionesAdmin.as_view(), name="listarPublicacionesAdmin"),

    path('agregarpublicacion', views.AgregarPublicacion.as_view(), name="agregarPublicacion"),

    path('detallepublicacion/<int:pk>', views.DetallePublicacion, name="detallePublicacion"),

    path('modificarpublicacion/<int:pk>', views.ModificarPublicacion, name="modificarPublicacion"),

    path('eliminarpublicacion/<int:pk>', views.EliminarPublicacion.as_view(), name="eliminarPublicacion"),

    path('eliminarvideo/<int:pk>', views.EliminarVideo, name="eliminarVideo"),

    path('eliminarPDF/<int:pk>', views.EliminarPDF, name='eliminarPdf'),
]

feriacultiva/feriacultiva/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administrador/', views.Administrador, name="panelAdmin"),

    #URL Principal
    path('', views.Inicio.as_view(), name="start"),
  
    path('registro/', include('apps.user.urls')),

    path('historia/', include('apps.historia.urls')),

    path('pedidos/', include('apps.pedido.urls')),

    path('reservas/', include('apps.reserva.urls')),

    path('publicaciones/', include('apps.publicaciones.urls')),

    path('producto/', include('apps.producto.urls')),

    path('feriantes/', include('apps.feriante.urls')),

    path('eventos/', include('apps.evento.urls')),

    path('temas/', include('apps.tema.urls')),

    path('comentario/', include('apps.comentario.urls')),

    path('vote/', include('apps.vote.urls')),

    # path('reserva/', include('apps.reserva.urls')), #

    #LOGIN and LOGOUT
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

feriacultiva/templates/Publicacion/detallePublicacion.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %} Ambiente y Salud {% endblock titulo%}
{% block contenido %}  
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'css/informativa.css' %}">
</head>

<section class="my-1">
	<div class="container" style="padding-top: 75px;">
		<h1 style="text-align: center;">{{object.titulo}}</h1>

      <div class="row align-items-center">
      <!-- Muestra todos los videos de la publicacion -->
      {% if vid|length != 0 %}
        {% for p in vid %}
        <div class="col-lg-6 order-lg-2">
          <iframe width="560" height="315" src="{{p.link_video}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
          </iframe>
        </div>
        {% endfor %}
          <div class="col-lg-6 order-lg-1">
              <div class="p-4">
                <p class="texto" style="text-align: center;">{{object.contenido}}</p>
              </div>
          </div>
      {% endif %}

        <!-- Todos los pdf que cotiene la publicacion -->
        {% if pdf|length != 0 %}
          {% for q in pdf %}
            <div class="col-lg-6 order-lg-1">
              <div class="p-4">
                <!-- <object data="{% static '../media/' %}{{q.pdf}}" style="width: 500px; height: 550px;">
                </object> -->
                <object  data="{% static 'img/archivo.pdf' %}" style="width: 500px; height: 550px;"></object>
              </div>
            </div>
          {% endfor %}
            <div class="col-lg-6 order-lg-2">
              <div class="p-4">
                <p class="texto">{{object.contenido}}</p>
              </div>
            </div>
        {% endif %}
    </div>
			
	</div>
</section>

{% endblock contenido%}

<!-- <a href="{% url 'publicacion:modificarPublicacion' object.pk %}">modificar</a>
			<a href="{% url 'publicacion:eliminarPublicacion' object.pk %}">eliminar</a> -->

feriacultiva/templates/Publicacion/editarPublicacion.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
 <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximun-scale=1.0, minimun-scale=1.0, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Latest compiled and minified CSS -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" comrossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Fuente google font-->
     <link href="https://fonts.googleapis.com/css?family=Roboto+Slab&display=swap" rel="stylesheet">
    <!-- Estilo css-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">

    
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-- icono de la página -->
    <link rel="icon" href="{% static 'img/logo.png' %}" type="image/x-icon">
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <!-- título de la pestaña-->
    <title>Lista de publicaciones</title>
  </head>


  <body style='font-family: "Roboto Slab", serif;' >
  <!--navbar admin-->
   <nav class="navbar navbar-expand-lg fixed-top" style="background-color: #283739;">
    <div class="container">
      <a class="navbar-brand" style="color: #f5f5f5;" href="{% url 'start' %}">Feria Cultiva</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon" style="color: #f5f5f5;"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'start' %}">Ir al sitio
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
                <a class="nav-link" href=" {% url 'publicacion:listarPublicacionesAdmin' %} "> Volver </a>
          </li>
         <li class="nav-item">
                <a class="nav-link" href="#"></a>
              </li>
              <li class="nav-item dropdown">
                {% if user.is_authenticated %}
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Hola! {{user.username}}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'logout' %}">Cerrar sesión</a>
                </div>
                {% endif %}
            </li>
        </ul>
      </div>
    </div>
  </nav>



<section class="py-5" >
  <!-- titulo y subtitulo de la pagina -->
<div class="container">
	<div class="title col-md-12 mx-auto">
    	<h3 class="text-center" style="margin-top: 30px; margin-bottom: 30px;">DETALLE DE PUBLICACIÓN</h3>
  	</div>
  	<!-- <div class="row">
  		<div class="col-md-4 mx-auto" style="text-align: center; margin-top: 30px;">
  			 {% if public.foto %}
                <img class="imagen-detalle" src="{{public.foto.url}}"  alt="imagen" style="width: 300px;">
              {% else %}
                <img class="imagen-detalle" src="" alt="No existe imagen" style="width: 250px; height: 400px; ">
              {% endif %}
        </div>
        <div class="col-md-8 mx-auto"> -->
		<form method="POST" enctype="multipart/form-data"> {% csrf_token %}
				
            <label for="titulo">Titulo</label>
            <input type="text" name="titulo" id="titulo" value="{{public.titulo}}">
            <div class="col-md-6 w-75 text-center">
                <label >Foto:</label> <br>
                   {% if public.foto %}
                        <img class="foto rounded-circle" src="{{public.foto.url}}" alt="foto">
                        {% else %}
                        <img src="" alt="no existe">
                    {% endif %} 
                <input type="file" name="foto" id="foto" value="{{public.foto.url}}"><br> 
            </div>
            <label for="contenido"></label>
            <input type="text" name="contenido" id="contenido" value="{{public.contenido}}">

            <form2>
                <label> Video: </label>
                <input type="text" name="link_video" id="link_video">
            </form2>

            <form3>
                <label>Documento: </label>
                <input type="file" name="pdf" id="pdf">
            </form3>

			  <div class="text-center" >
          <button class="btn mx-auto" type="submit">Guardar</button>
    		</div>
		</form>
		</div>
  </div>
  
  <!-- El formulario de los demas videos que tiene la publicacion.. tiene que estar afuera del principal form porque o sino no funciona -->
  {% if vid|length != 0 %}
    {% for p in vid %}
      <div>
        <label for="video">{{p.link_video}} {{p.pk}}</label>
        <form action="{% url 'publicacion:eliminarVideo' p.pk %}" method="POST" style="display: inline-block; padding-bottom: 100px;">
          {% csrf_token %}
            <button class="btn-eliminar" type="submit" href="" style="display: inline-block;">Eliminar</button>
        </form>
      </div>

    {% endfor %}
  {% endif %}

<!-- Todos los pdf que cotiene la publicacion -->
  {% if pdf|length != 0 %}
    {% for q in pdf %}
      <div>
        <label>{{q.pdf}}</label>
        <form action="{% url 'publicacion:eliminarPdf' q.pk %}" method="POST" style="display: inline-block; padding-bottom: 100px;">
          {% csrf_token %}
            <button class="btn-eliminar" type="submit" href="" style="display: inline-block;">Eliminar</button>
        </form>
        <div class="col-lg-6 order-lg-2">
          <div class="p-4">
          	<object  data="{% static '../media/' %}{{q.pdf}}" style="width: 500px; height: 600px;"></object>
          </div>
        </div>
      </div>
    {% endfor %}
  {% endif %}

  
  </div>  <!-- /fin container -->     
</section>
<footer class="fixed-bottom" style="background-color: #283739; height: 60px;">
        <div class="container">
          <p class="m-0 text-center text-white" style="color: #f5f5f5; padding-top: 17px;">Copyright &copy; IT4Connect 2019</p>
        </div>
</footer>


  <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

    <!-- video -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


</body>
</html>

feriacultiva/templates/Publicacion/eliminarPublicacion.html
	{% block contenido %}

	<form method="POST">
		{% csrf_token %}
		<div class="alert alert-danger mt-5 ml-3 mr-3" role="alert">Estas seguro que quieres eliminar la publicación {{ object.titulo }}?</div>
		<button class="btn btn-danger ml-3" type="submit">Si</button>
	</form>



	{% endblock contenido %}

feriacultiva/templates/Publicacion/listarPublicaciones.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %} Ambiente y Salud {% endblock titulo%}
{% block contenido %}  
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'css/informativa.css' %}">
</head>

<header class="masthead" style="background-image: url({% static 'img/A4.png' %}) ">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12 text-center">
      <h1 class="my-1 titulo-h1 ">
        Ambiente y salud
       </h1>
        <p class="lead"></p>
      </div>
    </div>
  </div>
</header>




<section class="py-5"><!-- Page Content -->
	<div class="container"><!-- Container página principal -->
    <div class="row">
      <div class="col-md-12"> 
        <div class="panel">
         {% for p in object_list %}
            <div class="row">    
              <br>
                <div class="col-md-3 col-sm-3 text-center">
                   <a class="story-img" href="{% url 'publicacion:detallePublicacion' p.pk %}">
                  <img src="{{p.foto.url}}" class="rounded" style="width: 250px;"></a>
                </div>
              <div class="col-md-8 col-sm-9">
                <h2 class="subt">{{p.titulo}}</h2>
                <div class="row">
                  <div class="col-xs-9">
                    <p class="texto">{{p.contenido}}</p>
                    <p><a href="{% url 'publicacion:detallePublicacion' p.pk %}">Ver más</a></p>          
                  </div>
                  <div class="col-xs-3">
                  </div>
                </div>
                <br><br>
              </div>
            </div>
          <hr>
      {% endfor %}
    </div>
      </div>
    </div>
  </div>
</section>

{% endblock contenido%}


<!-- {% if object_list|length != 0 %}
	{% for p in object_list %}
	<div class="row">
		<label for="">{{p.foto}}</label>
		<label for="">{{p.titulo}}</label>
		<label for="">{{p.contenido}}</label>
	</div>
	<a href="{% url 'publicacion:detallePublicacion' p.pk %}">ver</a>
	{% endfor %}
{% else %}
	<label for="">No publicaciones</label>
{% endif %}<a href="{% url 'publicacion:agregarPublicacion' %}">agregar</a> -->

feriacultiva/templates/Publicacion/listarPublicacionesAdmin.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
 <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximun-scale=1.0, minimun-scale=1.0, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Latest compiled and minified CSS -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" comrossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Fuente google font-->
     <link href="https://fonts.googleapis.com/css?family=Roboto+Slab&display=swap" rel="stylesheet">
    <!-- Estilo css-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">

    
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-- icono de la página -->
    <link rel="icon" href="{% static 'img/logo.png' %}" type="image/x-icon">
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <!-- título de la pestaña-->
    <title>Lista de publicaciones</title>
  </head>


  <body style='font-family: "Roboto Slab", serif;' >
  <!--navbar admin-->
   <nav class="navbar navbar-expand-lg fixed-top" style="background-color: #283739;">
    <div class="container">
      <a class="navbar-brand" style="color: #f5f5f5;" href="{% url 'start' %}">Feria Cultiva</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon" style="color: #f5f5f5;"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'start' %}">Ir al sitio
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
                <a class="nav-link" href=" {% url 'panelAdmin' %} "> Volver </a>
          </li>
         <li class="nav-item">
                <a class="nav-link" href="#"></a>
              </li>
              <li class="nav-item dropdown">
                {% if user.is_authenticated %}
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Hola! {{user.username}}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'logout' %}">Cerrar sesión</a>
                </div>
                {% endif %}
            </li>
        </ul>
      </div>
    </div>
  </nav>



<section class="py-5" >
  <!-- titulo y subtitulo de la pagina -->
<div class="container">

  <div class="title col-md-12 mx-auto">
    <h3 class="text-center" style="margin-top: 50px;">LISTADO DE PUBLICACIONES</h3>
  </div>
 
  <div class="row"> 
    <div class="container h-100 mx-auto" style="padding-top: 15px; padding-bottom: 15px;" >

      {% if object_list|length == 0 %}
        <label for="">No hay publicaciones para mostrar.</label>

        <div class="" style="padding-top: 30px;">
                <a href="{% url 'publicacion:agregarPublicacion' %}">
                  <button  class="btn mx-auto" type="submit">Nueva publicación</button></a>

        </div>

      {% else %}


      <table class="table table-hover table-borderless  shopping-cart-wrap mx-auto w-80">
        <thead class="text-muted" style="">
          <tr style="border-bottom: #a9c52f 2px solid; border-top:  #a9c52f 2px solid; ">
                  <th scope="col" width="150" class="title_table text-center">ID</th>
                  <th scope="col" width="100" class="title_table mx-auto">TÍTULO</th>
                  <th scope="col" width="50" class="title_table mx-auto">EDITAR</th>
                  <th scope="col" width="50" class="title_table mx-auto">ELIMINAR</th>
          </tr>
        </thead>
          <tbody>

                {% for p in object_list %}
                <tr>
                  <th scope="row" class="contenido_table text-center">{{p.pk}}</th>
                  <th scope="row" class="contenido_table">{{p.titulo}}</th>
                  <th scope="row" class="contenido_table">
                    <a href="{% url 'publicacion:modificarPublicacion' p.pk %}" style="color: #71a95a;" role="link" class="btn-link">Editar</a> 
                  </th>

                  <th scope="row">
        <!-- Botón en HTML (lanza el modal en Bootstrap) -->
          <a href="#victorModal{{p.pk}}" style="color: #da2d2d;" role="link" class="btn-link" data-toggle="modal">Eliminar</a>
                      <!-- Modal / Ventana / Overlay en HTML -->
          <div id="victorModal{{p.pk}}" class="modal fade">
           <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title">¿Estás seguro?</h4>
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>   
                </div>
              <div class="modal-body">
               <p>¿Seguro que quieres borrar este elemento?</p>
                <p class="text-warning"><small>Si lo borras, no podrás recuperarlo.</small></p>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn" data-dismiss="modal">Cerrar</button>
                                    
                <form action="{% url 'publicacion:eliminarPublicacion' p.pk %}" method="POST">
                {% csrf_token %}
                <button class="btn" type="submit" href="">eliminar</button>
                </form>
              </div>
            </div>
          </div>


                  </th>

                </tr>
                
                {% endfor %}  
              </tbody>
            </table>
        <div class="" style="padding-top: 30px;">
                <a href="{% url 'publicacion:agregarPublicacion' %}">
                  <button  class="btn mx-auto" type="submit">Nueva publicación</button></a>

        </div>
      {% endif %}

    </div>
   </div><!--fin row-->
  </div>  <!-- /fin container -->     
</section>
<footer class="fixed-bottom" style="background-color: #283739; height: 60px;">
        <div class="container">
          <p class="m-0 text-center text-white" style="color: #f5f5f5; padding-top: 17px;">Copyright &copy; IT4Connect 2019</p>
        </div>
</footer>


  <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

    <!-- video -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


</body>
</html>