feriacultiva/apps/feriante/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "feriante"

urlpatterns = [

    #URL Principal
    path('agregarFeriante/', views.AgregarFeriante.as_view(), name="agregar"),

    path('', views.ListarFeriantes.as_view(), name="listarFeriantes"),

    path('eliminar/<int:pk>', views.EliminarFeriante, name="eliminarFeriante"),

    path('listaFeriantes', views.ListarFeriantesWeb.as_view(), name="feriantesWeb"),

    path('detalleFeriante/<int:pk>', views.DetalleFeriante.as_view(), name="detalle"),

    path('correo/', views.EnviarCorreo, name="correo"),

    path('MisProductos/', views.MisProductos, name='MisProductos'),

    path('PerfilFeriante/', views.PerfilFeriante, name='PerfilFeriante'),



]

feriacultiva/apps/producto/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'producto'

urlpatterns = [
    path('', views.ListarProductos.as_view(), name = "ListarProducto"),
    path('Detalle/<int:pk>/<str:categoria>', views.DetalleProducto.as_view(), name='Detalle'),
    path('agregar/', views.AgregarProducto, name="agregar"),
    path('z', views.ListarProductos.as_view(), name="listar"),
    path('detalle/<int:pk>', views.DetalleProducto.as_view(), name="detalle"),
    path('modificar/<int:pk>', views.ModificarProducto.as_view(), name="modificar"),
    path('eliminar/<int:pk>', views.EliminarProducto.as_view(), name="eliminar"),
    path('misproductos/', views.MisProductos, name="MisProductos"),
]

feriacultiva/feriacultiva/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administrador/', views.Administrador, name="panelAdmin"),

    #URL Principal
    path('', views.Inicio.as_view(), name="start"),
  
    path('registro/', include('apps.user.urls')),

    path('historia/', include('apps.historia.urls')),

    path('pedidos/', include('apps.pedido.urls')),

    path('reservas/', include('apps.reserva.urls')),

    path('publicaciones/', include('apps.publicaciones.urls')),

    path('producto/', include('apps.producto.urls')),

    path('feriantes/', include('apps.feriante.urls')),

    path('eventos/', include('apps.evento.urls')),

    path('temas/', include('apps.tema.urls')),

    path('comentario/', include('apps.comentario.urls')),

    path('vote/', include('apps.vote.urls')),

    # path('reserva/', include('apps.reserva.urls')), #

    #LOGIN and LOGOUT
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

feriacultiva/apps/feriante/models.py
from django.db import models
from apps.user.models import User
# Create your models here.
class Feriante(models.Model):
	descripcion = models.TextField(max_length=500)
	foto_feriante = models.ImageField(upload_to = 'feriante', default='cliente/user.png')
	delivery = models.BooleanField(default=False, blank=True, null=True)
	encargado = models.OneToOneField(User, on_delete=models.CASCADE)


	def __str__(self):
		return self.encargado.first_name

feriacultiva/apps/feriante/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from apps.user.models import User
from django.contrib.auth.models import Group
from .models import Feriante

class FerianteForm(UserCreationForm):

	#descripcion = forms.CharField(label=("Descripción"), required=True)
	#foto_feriante = forms.ImageField(required=False)
	#delivery = forms.BooleanField(required=False)

	'''
	descripcion = models.TextField()
	foto_feriante = models.ImageField(upload_to = 'feriante', null = True)
	delivery = models.BooleanField(default=False)
	encargado = models.OneToOneField(User, on_delete=models.CASCADE)
	'''

	class Meta:
		model = User
		#fields = ['username','first_name','last_name','password','foto_perfil','email','direccion']
		fields = ['username','first_name','last_name','password1','password2','telefono','email']

	@transaction.atomic
	def save(self):
		user = super().save(commit=False)
		user.es_empresa = True
		user.username = self.cleaned_data.get('username')
		user.is_staff = True
		p = Group.objects.get(name = 'feriante')
		user.save()
		p.user_set.add(user)
		empresa = Feriante.objects.create(descripcion = 'vacio',encargado = user)
		return user



class PerfilFerianteForm(forms.ModelForm):

	class Meta:
		model = Feriante
		fields = ['foto_feriante','descripcion','delivery']

class PerfilUsuarioFeriante(forms.ModelForm):

	class Meta:
		model = User
		fields = ['first_name','direccion','telefono']

feriacultiva/apps/feriante/views.py
from django.shortcuts import render, redirect
from apps.feriante.models import Feriante
from apps.producto.models import Producto
from apps.user.models import User
from apps.pedido.models import Pedido
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy, reverse
from apps.feriante.forms import FerianteForm, PerfilFerianteForm, PerfilUsuarioFeriante
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.list import ListView
from django.core.paginator import Paginator
from django.views.generic.detail import DetailView
from apps.producto.models import Producto

from django.core.mail import send_mail



#vista para el template del administrador
class ListarFeriantes(ListView):
	model = Feriante
	template_name = 'Feriante/listarFeriantes.html'

#vista feriantes web
class ListarFeriantesWeb(ListView):
	model = Feriante
	paginate_by = 10
	template_name = 'Feriante/ListarFeriantesWeb.html'

	def get_context_data(self, **kwargs):
			context = super().get_context_data(**kwargs)
			paginator = context['paginator']
			page_numbers_range = 10 #Cantidad de página que se va a mostrar 
			max_index = len(paginator.page_range)

			page = self.request.GET.get('page')
			print (self.request)
			current_page = int(page) if page else 1

			start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
			end_index = start_index + page_numbers_range
			if end_index >= max_index:
				end_index = max_index

			page_range = paginator.page_range[start_index:end_index]
			context['page_range'] = page_range
			print("Anónimo: ",self.request.user.username)
			try:
				pedidos = Pedido.objects.filter(cliente = self.request.user)
			except Exception as e:
				pedidos = []

			context['Pedido'] = pedidos

			return context

#Vistas basadas en clases
class AgregarFeriante(SuccessMessageMixin, LoginRequiredMixin,CreateView): 
	model = Feriante
	form_class = FerianteForm
	template_name = 'Admin/agregarFeriante.html'
	success_url = reverse_lazy('feriante:agregar')
	success_message = 'Feriante agregado correctamente'

@login_required
def EliminarFeriante(request,pk):
	print(pk)
	usuario = Feriante.objects.get(pk = pk).encargado
	print(usuario)
	usuario.is_active = False
	usuario.save()
	return redirect('feriante:listarFeriantes')


# Esto es lo nuevo.. debo seguir trabajando
def PerfilFeriante(request):
	encargado = request.user
	feria = Feriante.objects.get(encargado = encargado)
	p = User.objects.get(username = encargado)
	print(p)
	context = {}
	context['feria'] = feria
	context['usuario'] = p
	print('hola')

	if request.method == 'GET':
		form = PerfilFerianteForm(instance = feria)
		form2 = PerfilUsuarioFeriante(instance = p)
		print('1')
	else:
		form = PerfilFerianteForm(request.POST,request.FILES, instance = feria)
		form2 = PerfilUsuarioFeriante(request.POST,request.FILES, instance = p)
		print('post')
		if form.is_valid and form2.is_valid():
			print('is_valid')
			perfil = form.save(commit = False)
			u = form2.save(commit = False)
			perfil.encargado = p
			if request.POST.get('foto_feriante') == '':
				perfil.foto_feriante = feria.foto_feriante
			else:
				perfil.foto_feriante = request.FILES.get('foto_feriante')
			perfil.descripcion = request.POST.get('descripcion')
			if request.POST.get('delivery') == 'Si':
				perfil.delivery = True
			else:
				perfil.delivery = False

			u.first_name = request.POST.get('first_name')
			u.direccion = request.POST.get('direccion')
			u.telefono = request.POST.get('telefono')
			u.save()
			perfil.save()
			return redirect(reverse('feriante:detalle',kwargs={'pk':feria.pk}))
	return render(request,'Feriante/perfil.html',context,{'form':form,'form2':form2})
	


class DetalleFeriante(DetailView):
	model = Feriante
	template_name = 'Feriante/detalle_feriante.html'

	def MisProductos(self, request, pk):
		context = {}
		usuario = Feriante.objects.get(pk = self.kwargs['pk'])
		print("ESTA ES LA PK", usuario)
		productos = Producto.objects.filter(feriante = usuario )
		context['object_list'] = productos
		print( context)

		return context

	def get_context_data(self,**kwargs):
		context = super().get_context_data(**kwargs)
		p = Producto.objects.filter(feriante = self.kwargs['pk'])
		context['product'] = p
		return context


def MisProductos(request):
	context = {}
	feriante2 = Feriante.objects.get(encargado = request.user)
	print(feriante2)
	p = Producto.objects.filter(feriante = feriante2)
	context['product'] = p
	print(context)
	return render(request,'Feriante/MisProductos.html',context)


# Esta funcion envia un correo
def EnviarCorreo(request):
	send_mail('Prueba', # titulo
		'Esto es un correo de prueba', # mensaje
		'feriacultivasite@gmail.com', 
		['flechaverde_s88@hotmail.com','mauriypachi@hotmail.com'], # Para:
		fail_silently=False,
	)
	return render(request,'Producto/listar.html')

feriacultiva/templates/Feriante/MisProductos.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %} Productos {% endblock titulo%}
{% block contenido %}  
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'css/productos.css' %}">
</head>

<header class="masthead" style="background-image: url({% static 'img/productos.jpg' %}) ">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12 text-center">
        <h1 class="font-weight-light">  </h1>
        <p class="lead"></p>
      </div>
    </div>
  </div>
</header>


<section class="py-5"><!-- Page Content -->
  <div class="container"><!-- Container página principal -->
       <h1 class="my-4">Productos >
       <small>Mis Productos</small>
       </h1>
  <div class="row">

   <!-- row página principal -->
    <div class="col-12">
    {% if user.es_empresa %}
      <button class="btn float-right" type="button"  >
        <a href="{% url 'producto:agregar' %}">
        Nuevo</a>
      </button>
    {% endif %}
    </div>  
      <div class="col-lg-9 mx-auto">
        <div class="row">
           {% if product|length == 0 %}
           <label for="">No hay productos para esta categoria</label>
            {% else%}
                {% for p in product %}
                  <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                      <a href="{% url 'producto:Detalle' p.pk p.categoria.nombre %}" class="imagen" >
                        {% if p.foto_producto %}
                                <img class="img-prod" style="width: 80px; height: 150px;" 
                                src="{{p.foto_producto.url}}" alt="encontre">
                            {% else %}
                                <img class="img-prod" style="width: 80px; height: 150px;" 
                                src="" alt="No existe imagen" >
                        {% endif %}
                        </a>
                      <div class="card-body">
                        <h4 class="card-title">
                          <a class="ancla-titulo" href="{% url 'producto:Detalle' p.pk p.categoria.nombre %}" class="imagen"> {{p.nombre}} </a>
                        </h4>
                        <h5 class="prod"> ${{p.precio}} </h5>
                        <p class="card-text"> Stock: {{p.stock}} </p>
                      </div>
                    </div>
                  </div>
                {% endfor %}
              {% endif %}

        </div> <!-- /.row col-lg-9 -->
      </div><!-- /.col-lg-9 -->

    </div> <!-- /.row contenido principal-->
   
  </div>    <!-- /.container -->    
</section>
{% endblock contenido%}

feriacultiva/templates/Feriante/detalle_feriante.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %} Detalle Feriantes {% endblock titulo%}
{% block contenido %}  
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/det-feriante.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">
    
</head>

<!-- contenido de la página -->
<section class="py-5" >
<!-- Page Content -->
  <div class="container">
   <!-- Portfolio Item Heading -->
    <h1 class="my-1 ">FERIA CULTIVA</h1>
    <h1 class="feriante-titulo">{{object.encargado.first_name}}</small></h1>
    
    <div class="row detalle-card" >
        <div class="col-md-6" >
              <!--contenedor de la imagen-->
          <div class="card mb-3" id="card-detalle">
            <div class="row no-gutters">
              <div id="demo" class="carousel slide" data-ride="carousel">

                 <!-- Indicators -->
                  <ul class="carousel-indicators">
                    <li data-target="#demo" data-slide-to="0" class="active"></li>
                    <li data-target="#demo" data-slide-to="1"></li>
                    <li data-target="#demo" data-slide-to="2"></li>
                  </ul>
                 <!-- The slideshow -->
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <img src="https://image.freepik.com/foto-gratis/greengrocer-que-vende-productos-agricolas-frescos-organicos-mercado-granjero_53876-10103.jpg" width="100%" alt="Ejemplo1">
                    </div>
                    <div class="carousel-item">
                      <img src="https://image.freepik.com/foto-gratis/close-up-mujer-cosechando-zanahorias_23-2148256630.jpg" width="100%" alt="Ejemplo2"> 
                    </div>
                    <div class="carousel-item">
                      <img src="https://img.freepik.com/foto-gratis/verduras-crudas-cesta_23-2147694075.jpg?size=626&ext=jpg" width="100%" alt="ejemplo3">
                    </div>
                  </div>
                <!-- Left and right controls -->
                  <a class="carousel-control-prev" href="#demo" data-slide="prev">
                     <span class="carousel-control-prev-icon"></span>
                  </a>
                  <a class="carousel-control-next" href="#demo" data-slide="next">
                    <span class="carousel-control-next-icon"></span>
                  </a>
              </div>
              <!-- <div class="col-md-4" >
             {% if object.foto_feriante %}
                <img class="imagen-detalle" src="{{object.foto_feriante.url}}"  alt="imagen" style="width: 500px; height: 350px;"  >
              {% else %}
                <img class="img-mi-detalle" src="" alt="No existe imagen" style="width: 250px; height: 400px; ">
              {% endif %} 
              </div> -->
            </div>
          </div>   
      </div>
    <!--descripción -->
      <div class="col-md-6" style="padding-top: 50px;">
        <h5 class="detalle-titulo">NOSOTROS </h5>
        <p class="card-text-det">{{object.descripcion}}</p>
        <h5 class="detalle-titulo">CONTACTANOS </h5>
        <p class="card-text-det"> <i class="fas fa-phone"></i> {{object.encargado.telefono}}</p>
        <p class="card-text-det"> <i class="fas fa-envelope-square"></i>  {{object.encargado.email}}</p>
        <div class="">
          {%  if object.delivery == False %}
          <p class="item-d mx-auto">NO HACEMOS ENTREGA A DOMICILIO</p>
          {% else %}
          <p class="item-d mx-auto">HACEMOS ENTREGA A DOMICILIO
            <span class="glyphicon glyphicon-ok"></span>
          </p>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <h1 class="my-1">Más sobre nosotros</h1>
      <div class="row">
        <div class="mx-auto">
        <iframe width="705" height="341" src="https://www.youtube.com/embed/fQk5Shse42k" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
      </div>
    </div>


  

  <!-- ERA LA GALERIA DE PRODUCTOS DEL FERIANTE :(
  <div class="container-fluid">
     {% if product|length > 0 %}
    <h1 class="my-1 ">
     NUESTROS PRODUCTOS
    </h1>
     <div class="row row-productos" >
    
             {% for p in product %}
               <div class="col-lg-3 col-md-3 mx-auto"  style="padding-bottom: 70px;">

                 <div class="card h-100" >
                   <a href="{% url 'producto:Detalle' p.pk p.categoria.nombre %}" class="imagen" >
                     {% if p.foto_producto %}
                             <img class="img-prod" style="width: 80px; height: 150px; " 
                             src="{{p.foto_producto.url}}" alt="encontre">
                         {% else %}
                             <img class="img-prod" style="width: 80px; height: 150px;" 
                             src="" alt="No existe imagen" >
                     {% endif %}
                     </a>
                   <div class="card-body mx-auto">
                     <h4 class="card-title">
                       <a href="{% url 'producto:Detalle' p.pk p.categoria.nombre %}" class="imagen-titulo-card "> {{p.nombre}} </a>
                     </h4>
                   </div>
                 </div>
               </div>
             {% endfor %}
           
    </div>
   {% endif %}
</div>fin del las cards container fluid -->
    
  </div>

   

</section>

{% endblock contenido%}

feriacultiva/templates/Feriante/email.html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
    <h1>{{user_name}}</h1>
    <p>El usuario {{user_name}} quiere reservar este producto:</p>
    <h3>{{producto_name}}</h3>
    <img src={{foto_producto}} alt="">
    <p>cantidad: {{cantidad}}</p>
    <p>Comunicate con el para confirmar su pedido enviando un correo a:  <a href="">{{email}}</a></p>
</body>
</html>

feriacultiva/templates/Feriante/listarFeriantes.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
 <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximun-scale=1.0, minimun-scale=1.0, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Latest compiled and minified CSS -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" comrossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Fuente google font-->
     <link href="https://fonts.googleapis.com/css?family=Roboto+Slab&display=swap" rel="stylesheet">
    <!-- Estilo css-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">

    
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-- icono de la página -->
    <link rel="icon" href="{% static 'img/logo.png' %}" type="image/x-icon">
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <!-- título de la pestaña-->
    <title>Listar Feriantes</title>
  </head>


  <body style='font-family: "Roboto Slab", serif;' >
  <!--navbar admin-->
   <nav class="navbar navbar-expand-lg fixed-top" style="background-color: #283739;">
    <div class="container">
      <a class="navbar-brand" style="color: #f5f5f5;" href="{% url 'start' %}">Feria Cultiva</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon" style="color: #f5f5f5;"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'start' %}">Ir al sitio
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
                <a class="nav-link" href=" {% url 'panelAdmin' %} "> Volver </a>
          </li>
         <li class="nav-item">
                <a class="nav-link" href="#"></a>
              </li>
              <li class="nav-item dropdown">
                {% if user.is_authenticated %}
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Hola! {{user.username}}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'logout' %}">Cerrar sesión</a>
                </div>
                {% endif %}
            </li>
        </ul>
      </div>
    </div>
  </nav>



<section class="py-5">
  <!-- titulo y subtitulo de la pagina -->
<div class="container">

   <div class="title col-md-12 mx-auto">
    <h3 class="text-center" style="margin-top: 50px;">LISTADO DE FERIANTES</h3>
   </div>
   <div class="row"> 
    <div class="container h-100 mx-auto" style="padding-top: 15px; padding-bottom: 15px;" >

      {% if object_list|length == 0 %}
        <label for="">No hay feriantes.</label>

      {% else %}


      <table class="table table-hover table-borderless  shopping-cart-wrap mx-auto w-80">
        <thead class="text-muted" style="">
          <tr style="border-bottom: #283739 2px solid; border-top:  #283739 2px solid; ">
                  <th scope="col" width="150" class="title_table text-center">ID</th>
                  <th scope="col" width="100" class="title_table mx-auto">FERIANTES</th>
                  <th scope="col" width="50" class="title_table mx-auto">ELIMINAR</th>
          </tr>
        </thead>
          <tbody>

                {% for p in object_list %}
                {% if p.encargado.is_active %}
                <tr>
                  <th scope="row" class="contenido_table text-center">{{p.pk}}</th>
                  <th scope="row" class="contenido_table">{{p.encargado.first_name}}</th>

                  <th scope="row">
        <!-- Botón en HTML (lanza el modal en Bootstrap) -->
          <a href="#victorModal{{p.pk}}" style="color: #da2d2d;" role="link" class="btn-link" data-toggle="modal">Eliminar</a>
                      <!-- Modal / Ventana / Overlay en HTML -->
          <div id="victorModal{{p.pk}}" class="modal fade">
           <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title">¿Estás seguro?</h4>
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>   
                </div>
              <div class="modal-body">
               <p>¿Seguro que quieres borrar este elemento?</p>
                <p class="text-warning"><small>Si lo borras, no podrás recuperarlo.</small></p>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn" data-dismiss="modal">Cerrar</button>
                                    
                <form action="{% url 'feriante:eliminarFeriante' p.pk %}" method="POST">
                {% csrf_token %}
                <button class="btn" type="submit" href="">eliminar</button>
                </form>
              </div>
            </div>
          </div>


                  </th>

                </tr>
                {% endif %}
                {% endfor %}  
              </tbody>
            </table>
      {% endif %}

    </div>
      </div><!--fin row-->
  </div>  <!-- /fin container -->     
</section>
<footer class="fixed-bottom" style="background-color: #283739; height: 60px;">
        <div class="container">
          <p class="m-0 text-center text-white" style="color: #f5f5f5; padding-top: 17px;">Copyright &copy; IT4Connect 2019</p>
        </div>
</footer>


  <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

    <!-- video -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


</body>
</html>