feriacultiva/apps/evento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "evento"

urlpatterns = [

    path('', views.ListarEventos.as_view(), name="listarEventos"),

    path('ActualizarEvento', views.ListarEventosAdmin.as_view(), name="listarEventosAdmin"),

    path('agregarevento', views.AgregarEvento.as_view(), name="agregarEvento"),

    path('detalleevento/<int:pk>', views.DetalleEvento.as_view(), name="detalleEvento"),

    path('modificarevento/<int:pk>', views.ModificarEvento.as_view(), name="modificarEvento"),

    path('eliminarevento/<int:pk>', views.EliminarEvento.as_view(), name="eliminarEvento"),
]

feriacultiva/apps/feriante/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "feriante"

urlpatterns = [

    #URL Principal
    path('agregarFeriante/', views.AgregarFeriante.as_view(), name="agregar"),

    path('', views.ListarFeriantes.as_view(), name="listarFeriantes"),

    path('eliminar/<int:pk>', views.EliminarFeriante, name="eliminarFeriante"),

    path('listaFeriantes', views.ListarFeriantesWeb.as_view(), name="feriantesWeb"),

    path('detalleFeriante/<int:pk>', views.DetalleFeriante.as_view(), name="detalle"),

    path('correo/', views.EnviarCorreo, name="correo"),

    path('MisProductos/', views.MisProductos, name='MisProductos'),

    path('PerfilFeriante/', views.PerfilFeriante, name='PerfilFeriante'),



]

feriacultiva/apps/producto/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'producto'

urlpatterns = [
    path('', views.ListarProductos.as_view(), name = "ListarProducto"),
    path('Detalle/<int:pk>/<str:categoria>', views.DetalleProducto.as_view(), name='Detalle'),
    path('agregar/', views.AgregarProducto, name="agregar"),
    path('z', views.ListarProductos.as_view(), name="listar"),
    path('detalle/<int:pk>', views.DetalleProducto.as_view(), name="detalle"),
    path('modificar/<int:pk>', views.ModificarProducto.as_view(), name="modificar"),
    path('eliminar/<int:pk>', views.EliminarProducto.as_view(), name="eliminar"),
    path('misproductos/', views.MisProductos, name="MisProductos"),
]

feriacultiva/apps/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'usuario'

urlpatterns = [

    #URL Principal
    path('', views.RegistrarUsuario.as_view(), name="agregar"),

    path('editarperfil', views.EditarPerfil, name="editarperfil"),

    path('perfil', views.Perfil, name="perfil"),

]

feriacultiva/feriacultiva/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administrador/', views.Administrador, name="panelAdmin"),

    #URL Principal
    path('', views.Inicio.as_view(), name="start"),
  
    path('registro/', include('apps.user.urls')),

    path('historia/', include('apps.historia.urls')),

    path('pedidos/', include('apps.pedido.urls')),

    path('reservas/', include('apps.reserva.urls')),

    path('publicaciones/', include('apps.publicaciones.urls')),

    path('producto/', include('apps.producto.urls')),

    path('feriantes/', include('apps.feriante.urls')),

    path('eventos/', include('apps.evento.urls')),

    path('temas/', include('apps.tema.urls')),

    path('comentario/', include('apps.comentario.urls')),

    path('vote/', include('apps.vote.urls')),

    # path('reserva/', include('apps.reserva.urls')), #

    #LOGIN and LOGOUT
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

feriacultiva/templates/administrador.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximun-scale=1.0, minimun-scale=1.0, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Latest compiled and minified CSS -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" comrossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">


    <!-- Fuente google font-->
     <link href="https://fonts.googleapis.com/css?family=Roboto+Slab&display=swap" rel="stylesheet">
    <!-- Estilo css-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/admin.css' %}">
 
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-- icono de la página -->
    <link rel="icon" href="{% static 'img/logo.png' %}" type="image/x-icon">

    <!-- título de la pestaña-->
    <title>Panel de Administración</title>

  </head>
  
  <body style='font-family: "Roboto Slab", serif;'>
 
<header>
<!--navbar admin-->
  <nav class="navbar navbar-expand-lg fixed-top" style="background-color: #283739;">
    <div class="container">
      <a class="navbar-brand" style="color: #f5f5f5;" href="{% url 'start' %}">Feria Cultiva</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon" style="color: #f5f5f5;"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'start' %}">Ir al sitio
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
                <a class="nav-link" href="#"></a>
              </li>
              <li class="nav-item dropdown">
                {% if user.is_authenticated %}
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Hola! {{user.username}}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'logout' %}">Cerrar sesión</a>
                </div>
                {% endif %}
            </li>
        </ul>
      </div>
    </div>
  </nav>
  </header>
  
  <section style="padding: 15px; margin-bottom: 75px;">
   
      
    <div class="container-fluid mx-auto">

      <div class="col-lg-8 mx-auto" style="padding-top: 75px;">
              
        <div class="row">
          <div class="title mx-auto">
           <h3> BIENVENIDO AL PANEL DE ADMINISTRACION</h3> 
          </div>
          
          <div class="col-lg-6 col-xs-12 text-center">

            <div class="card bg-info">
            <a class="admin-acciones" href="{% url 'feriante:agregar' %}" class="contenidoCard">
              <img src="{% static 'img/feriante.png' %}" class="card-img w-25" alt="...">
                <div class="card-img-overlay">
                  <h5 class="card-title">Feriante</h5>
                  <p class="card-text">Agregar</p>
                </div>
              </a>
            </div>

            <div class="card bg-success">
              <a  class="admin-acciones" href="{% url 'publicacion:listarPublicacionesAdmin' %}" class="contenidoCard">
              <img src="{% static 'img/ambienteSalud.png' %}" class="card-img" alt="...">
                <div class="card-img-overlay">
                  <h5 class="card-title">Ambiente y salud</h5>
                  <p class="card-text">Actualizar contenido</p>
                </div>
              </a>
            </div>

          </div>

          <div class="col-lg-6 col-xs-12 text-center">
          
            <div class="card bg-warning">
              <a  class="admin-acciones" href="{% url 'feriante:listarFeriantes' %}" class="contenidoCard">
              <img src="{% static 'img/ferianteslistar.png' %}" class="card-img w-25" alt="...">
                <div class="card-img-overlay">
                  <h5 class="card-title">Lista de feriantes</h5>
                  <p class="card-text">Eliminar</p>
                </div>
              </a>
            </div>

            <div class="card bg-danger">
              <a class="admin-acciones" href="{% url 'evento:listarEventosAdmin' %}" class="contenidoCard">
              <img src="{% static 'img/evento.png' %}" class="card-img w-25" alt="...">
                <div class="card-img-overlay">
                  <h5 class="card-title">Información del evento</h5>
                  <p class="card-text">Actualizar</p>
                </div>
              </a>
            </div>

          </div>

          </div>
        </div>
      </div>
    </section>


      <footer class="fixed-bottom" style="background-color: #283739; height: 60px;">
        <div class="container">
          <p class="m-0 text-center text-white" style="color: #f5f5f5; padding-top: 17px;">Copyright &copy; IT4Connect 2019</p>
        </div>
      </footer>   
  </body>
     <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <!-- video -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </html>

feriacultiva/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block titulo%} - Iniciar sesión {% endblock titulo%}


{% block contenido %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>  

<!-- Page Content -->
<section class="py-5"  >
  <!-- Page Content -->
  <div class="container" style="margin-top: 110px; margin-bottom: 40px;">
		<div class="row">

			<div class="col-md-6">
				<img src="{% static 'img/loginnew.png' %}" class="w-100 h-100" style="opacity: 0.8;">
			</div>

			<div class="col-md-6">
    		<div class="container" style="margin-top: 80px;">
				<h4 class="text-center" id="tit">Iniciar sesión</h4>
				<br>
				<form action="{% url 'login' %}" method="POST">{% csrf_token %}
					<div class="form-group">
					    <label for="exampleInputEmail1" class="">Usuario</label>
					    <input type="text" class="form-control mx-auto" name="username" aria-describedby="emailHelp" placeholder="Ingrese usuario">
					</div>
					
					<div class="form-group">
					<label for="exampleInputPassword1" class="">Contraseña</label>
					  <div class="input-group">
					    <input ID="txtPassword" type="Password" class="form-control mx-auto" name="password" placeholder="Contraseña">
					    <div class="input-group-append">
				            <button id="show_password" class="btn btn-link" style="border-color: #a9c52f; " type="button" onclick="mostrarPassword()"> <span style="color: #283739;" class="fa fa-eye-slash icon"></span> </button>
				        </div>
					  </div>
					    <small id="emailHelp" class="form-text text-muted text-center">
						   	<a href="" class="boton">¿Olvidaste tu contraseña?</a>
						</small>
					</div>

					{% if form.errors %}
					<div class="alert alert-danger" role="alert">

 					 Nombre de usuario o contraseña incorrectos. Ingresá nuevamente.
						
					</div>
					{% endif %}
					  
					<input type="hidden" name="next" value="{{ next }}" />
					<div class="" style="text-align: center;">
						<button  type="submit" class="btn btn-log">Ingresar</button>
					</div>
					<small id="emailHelp" class="form-text text-muted text-center">
						   	<a href="{% url 'usuario:agregar' %}" class="boton">¿No tenés cuenta? Crear cuenta</a>
					</small>
				</form>
			</div>				
		</div>
	</div>
	</div>				
</section>
<script type="text/javascript">
function mostrarPassword(){
		var cambio = document.getElementById("txtPassword");
		if(cambio.type == "password"){
			cambio.type = "text";
			$('.icon').removeClass('fa fa-eye-slash').addClass('fa fa-eye');
		}else{
			cambio.type = "password";
			$('.icon').removeClass('fa fa-eye').addClass('fa fa-eye-slash');
		}
	} 
	
	$(document).ready(function () {
	//CheckBox mostrar contraseña
	$('#ShowPassword').click(function () {
		$('#Password').attr('type', $(this).is(':checked') ? 'text' : 'password');
	});
});
</script>
{% endblock contenido %}

feriacultiva/templates/start.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %} Inicio {% endblock titulo %}

  {% block contenido %}

<head>
    <!-- icono de la página -->
    <link rel="icon" href="{% static 'img/logo.png' %}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{% static 'css/productos.css' %}">
  
</head>
<header id="mi-header">
  <!-- slide page principal -->
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">

      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
     
    </ol>
    <div class="carousel-inner" role="listbox">
      <!-- Slide One - Set the background image for this slide in the line below -->
      <div class="carousel-item active" style="background-image: url({% static 'img/s1.png' %}) " >
        <div class="carousel-caption d-none d-md-block">
          <!-- <img id="logo"  src=""  class="d-inline-block align-top" alt="Feria Cultiva" ;> -->
          <img id=""  src="{% static 'img/logo con fondo circular.PNG' %}"  class="d-inline-block align-top" style="height: 106px;" alt="Feria Cultiva">
          <h2 class="titulo-1">Feria Cultiva</h2>
          <p class="lead">Productos agroecológicos</p>
          <div class="d-block mx-auto" style="text-align: left; width: 1200px;">
            <img id=""  src="{% static 'img/logo-INTA3.PNG' %}"  class="d-inline-block align-top inststart rounded" alt="Feria Cultiva">
            <img id=""  src="{% static 'img/logo-CECUAL.PNG' %}"  class="d-inline-block align-top inststart rounded" alt="Feria Cultiva">
            <img id=""  src="{% static 'img/logo-IndustriasCulturales.PNG' %}"  class="d-inline-block align-top inststart rounded" alt="Feria Cultiva">
            <img id=""  src="{% static 'img/logo-EspacioAlternativo.PNG' %}"  class="d-inline-block align-top inststart rounded" alt="Feria Cultiva">
            <img id=""  src="{% static 'img/logo-ICultura.PNG' %}"  class="d-inline-block align-top inststart rounded" alt="Feria Cultiva">
            <img id=""  src="{% static 'img/logo-Gob.PNG' %}"  class="d-inline-block align-top inststart rounded" alt="Feria Cultiva">
          </div>

        </div>
      </div>
      <!-- Slide Two - Set the background image for this slide in the line below -->
      <div class="carousel-item" style="background-image: url('{% static 'img/s2.png' %}')">
        <div class="carousel-caption d-none d-md-block">
          <!-- <img id="logo"  src="{% static 'img/letrasverdes.png' %}"  class="d-inline-block align-top" alt="Feria Cultiva" style="width: 250px;"> -->
        
          <h2 class="titulo-1">La feria en tiempos de cuarentena</h2>
          <p class="lead">Confiamos en que pronto volveremos a encontrarnos</p>
          <p class="lead">mientras tanto ¡Te invitamos a recorrer el sitio!</p>
          
         </div> 
      </div>
      <!-- Slide Three - Set the background image for this slide in the line below -->
      <div class="carousel-item" style="background-image: url('{% static 'img/s3.png' %}')">
        <div class="carousel-caption d-none d-md-block">
          <!-- <img id="logo"  src="{% static 'img/letrasverdes.png' %}"  class="d-inline-block align-top" alt="Feria Cultiva" style="width: 250px;"> -->
          <img id=""  src="{% static 'img/logo con fondo circular.PNG' %}"  class="d-inline-block align-top" style="height: 106px;" alt="Feria Cultiva">
          <h2 class="titulo-1">Conocé a los feriantes</h2>
          <p class="lead">Mirá los productos que ofrecen</p>
          <p class="lead">Comunicate para acordar la compra</p>
        </div>
      </div>
      <!-- Slide Three - Set the background image for this slide in the line below -->
      
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
  </div>
</header>

<!-- Page Content -->
<section class="py-1" >
<!--   <div class="col-lg-8 mx-auto " style="background-color:#fff;">
    <div class="container-fluid" >
           <h1 class="my-1 ">
            PRODUCTOS RECIENTES
           </h1>
      <div class="row">
           {% if object_list|length == 0 %}
           <label for="">No hay productos.</label>
          {% else%}
                {% for p in Recientes %}
                  <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                      <a href="{% url 'producto:Detalle' p.pk p.categoria.nombre %}" class="imagen" >
                        {% if p.foto_producto %}
                                <img class="img-prod" style="width: 100px; height: 150px;" 
                                src="{{p.foto_producto.url}}" alt="encontre">
                            {% else %}
                                <img class="img-prod" style="width: 80px; height: 150px;" 
                                src="" alt="No existe imagen" >
                        {% endif %}
                        </a>
                      <div class="card-body">
                        <h4 class="card-title">
                          <a class="ancla-titulo" href="{% url 'producto:Detalle' p.pk p.categoria.nombre %}" class="imagen"> {{p.nombre}} </a>
                        </h4>
                       <h5 class="prod"> ${{p.precio}} </h5>
                   
                      {% if p.stock > 0 %}
                        <p class="card-text"> Stock: {{p.stock}} </p>
                      {% else %}
                        <p class="card-text"> No hay stock disponible </p>
                      {% endif %} 

                      </div>
                     
                    </div>
                  </div>
                {% endfor %}
              {% endif %}

        </div>  /.row col-lg-9 -->

    

       

<!-- <div class="col-lg-8 mx-auto" style="padding-top: 50px;"  >

    <div class="box" >
        <h1 class="my-1 ">
               ¿CÓMO FUNCIONA ?
        </h1>
    <div class="container">
      <div class="row">
       
        <div class="col-lg-4 col-xs-12 text-center">
          <div class="box">
                        <img src="{% static 'img/paso1.png' %}" class="img-como-funciona">
            <div class="box-title">
              <h2 class="titulo-seccion">Elegí tus productos</h2>
            </div>
            <div class="box-text">
             <p>Seleccioná del catálogo los productos que quieras. Podés elegir los más recientes o andá a las sección de productos y selecciná la categoría que quieras. </p>
            </div>
            
           </div>
        </div>   
        
         <div class="col-lg-4 col-xs-12  text-center">
          <div class="box">
                        <img src="{% static 'img/paso2.png' %}" class="img-como-funciona">
            <div class="box-title">
                <h4 class="titulo-seccion">Hacé tus reservas </h4>
            </div>
            <div class="box-text">
                <p> Una vez que selecciones un producto, e ingreses la cantidad que quieras, pulsá sobre "Reservar", y se cargará tu pedido al listado de reservas. </p>
            </div>
            
           </div>
        </div>   
          
        
         <div class="col-lg-4 col-xs-12 text-center">
          <div class="box">
                        <img src="{% static 'img/paso3.png' %}" class="img-como-funciona">
            <div class="box-title">
               <h4 class="titulo-seccion">Controlá el estado</h4>
            </div>
            <div class="box-text">
              <p>A través de la página podés visualizar el estado de tus pedidos, el feriante va a confirmar tu reserva y se va a comunicar con vos para acordar la entrega.</p>
            </div>
           
           </div>
        </div>
    
    </div>    
    </div>
</div>
</div> -->


<div class="container-fluid categoria" >
          <h1 class="my-1 ">
              CATEGORÍAS
          </h1>
      

  <div class="container-fluid">
    <div class="row">
      {% for p in Categorias %}
          <div class="col-md-3 col-sm-3 col-xs-12 mx-auto" style="margin-bottom: 5px;">
             <div class="bg-white text-white">
                <img src=" {{p.foto.url}} " class="card-img-cat" alt="">
                <div class="card-img-overlay">
                  <h5 class="card-categoria mx-auto" >{{p.nombre}}</h5>
                </div>
              </div>
            </div>
        {% endfor %}
          </div>
    </div>
  </div>

<div class="container-fluid">  
  <div class="row mx-auto" style="margin-bottom: 20px;">
      <img class="mx-auto" src="{% static 'img/estampaCULTIVA.png' %}" style=" height: 500px;" alt="Feria Cultiva">
  </div>
</div>

</section>

{% endblock contenido %}