feriacultiva/apps/feriante/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "feriante"

urlpatterns = [

    #URL Principal
    path('agregarFeriante/', views.AgregarFeriante.as_view(), name="agregar"),

    path('', views.ListarFeriantes.as_view(), name="listarFeriantes"),

    path('eliminar/<int:pk>', views.EliminarFeriante, name="eliminarFeriante"),

    path('listaFeriantes', views.ListarFeriantesWeb.as_view(), name="feriantesWeb"),

    path('detalleFeriante/<int:pk>', views.DetalleFeriante.as_view(), name="detalle"),

    path('correo/', views.EnviarCorreo, name="correo"),

    path('MisProductos/', views.MisProductos, name='MisProductos'),

    path('PerfilFeriante/', views.PerfilFeriante, name='PerfilFeriante'),



]

feriacultiva/apps/producto/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'producto'

urlpatterns = [
    path('', views.ListarProductos.as_view(), name = "ListarProducto"),
    path('Detalle/<int:pk>/<str:categoria>', views.DetalleProducto.as_view(), name='Detalle'),
    path('agregar/', views.AgregarProducto, name="agregar"),
    path('z', views.ListarProductos.as_view(), name="listar"),
    path('detalle/<int:pk>', views.DetalleProducto.as_view(), name="detalle"),
    path('modificar/<int:pk>', views.ModificarProducto.as_view(), name="modificar"),
    path('eliminar/<int:pk>', views.EliminarProducto.as_view(), name="eliminar"),
    path('misproductos/', views.MisProductos, name="MisProductos"),
]

feriacultiva/feriacultiva/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administrador/', views.Administrador, name="panelAdmin"),

    #URL Principal
    path('', views.Inicio.as_view(), name="start"),
  
    path('registro/', include('apps.user.urls')),

    path('historia/', include('apps.historia.urls')),

    path('pedidos/', include('apps.pedido.urls')),

    path('reservas/', include('apps.reserva.urls')),

    path('publicaciones/', include('apps.publicaciones.urls')),

    path('producto/', include('apps.producto.urls')),

    path('feriantes/', include('apps.feriante.urls')),

    path('eventos/', include('apps.evento.urls')),

    path('temas/', include('apps.tema.urls')),

    path('comentario/', include('apps.comentario.urls')),

    path('vote/', include('apps.vote.urls')),

    # path('reserva/', include('apps.reserva.urls')), #

    #LOGIN and LOGOUT
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

feriacultiva/apps/producto/models.py
from django.db import models
from apps.categoria.models import Categoria
from apps.feriante.models import Feriante
# Create your models here.
class Producto(models.Model):
	nombre = models.CharField(max_length=30)
	descripcion = models.TextField(max_length=100)
	precio = models.DecimalField(max_digits=8, decimal_places=2)
	stock = models.IntegerField()
	foto_producto = models.ImageField(upload_to = 'productos', null = True)
	categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, related_name='productosXcategoria')
	feriante = models.ForeignKey(Feriante, on_delete=models.CASCADE, related_name='productosXferiante')

	def __str__(self):
		return self.nombre

feriacultiva/apps/producto/forms.py
from django import forms
from apps.producto.models import Producto
from apps.feriante.models import Feriante

class ProductoForm(forms.ModelForm):

	class Meta:
		model = Producto
		fields = ['nombre', 'precio', 'stock', 'foto_producto', 'categoria', 'descripcion']
	


'''


FORMULARIO COMPLETO PARA REVISAR

1- Como obtener el feriante
2- la categoria no me toma como válido


'''

feriacultiva/apps/producto/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin
from apps.producto.models import Producto
from apps.feriante.models import Feriante
from apps.categoria.models import Categoria
from apps.reserva.models import Reserva
from apps.pedido.models import Pedido
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from apps.producto.forms import ProductoForm
from apps.reserva.forms import ReservaForm
from apps.pedido.forms import PedidoForm
import collections
from decimal import Decimal
from django.db.models import Sum
from django.contrib import messages
from django.http import Http404

class ListarProductos(ListView):
	model = Producto
	paginate_by = 12
	template_name = 'Producto/listar.html'
	form_class = PedidoForm

	def post(self,request,*args,**kwargs):

		form = self.form_class(request.POST)
		print('anted de is_valid')
		pk = request.POST['Confirmar']
		print(pk)
		print('pk')

		if form.is_valid():
			x = Pedido.objects.filter(cliente = request.user)
			p = Producto.objects.get(pk = pk)
			try:
				pedido = Pedido.objects.get(cliente = request.user,producto = p)
				cant = request.POST.get('cantidad')
				total = Decimal(cant) * pedido.producto.precio
				suma = int(cant) + int(pedido.cantidad)
				if suma > 0:
					pedido.cantidad = int(cant) + int(pedido.cantidad)
					pedido.total = int(total) + int(pedido.total)
					pedido.save()
				print('p en pedido')
			except:
				p = Producto.objects.get(pk = pk)
				res = form.save(commit = False)
				res.producto = p
				res.cliente = request.user
				cant = request.POST['cantidad']
				if int(cant) > 0:
					total = Decimal(cant) * p.precio
					print('total')
					print(total)
					res.total = total
					res.save()
					print('Guardeeee')
			return HttpResponseRedirect('/producto/')
		return render(request,self.template_name, {'form':form})


	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		print (context)
		
		paginator = context['paginator']
		page_numbers_range = 10 #Cantidad de página que se va a mostrar 
		max_index = len(paginator.page_range)

		page = self.request.GET.get('page')
		print (self.request)
		current_page = int(page) if page else 1

		start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
		end_index = start_index + page_numbers_range
		if end_index >= max_index:
			end_index = max_index

		page_range = paginator.page_range[start_index:end_index]
		context['page_range'] = page_range
		context['filtro'] = Categoria.objects.all()

		if self.request.user.is_authenticated:
			pedidos = Pedido.objects.filter(cliente = self.request.user).aggregate(Sum('cantidad'))
			context['Pedido'] = pedidos

		buscar = self.request.GET.get("buscador")
		print(buscar)
		if buscar:
			context['object_list'] = Producto.objects.filter(nombre__icontains = buscar)

		return context

	def get_queryset(self):
		# context = {}
		categoria = self.request.GET.get('Categoria',None)
		if not categoria:
			categoria = "0"
		
		if categoria == "0":
			x = Producto.objects.all()
		else:
			x = Producto.objects.filter(categoria = categoria)
		return x
	


class AgregarProductoo(LoginRequiredMixin,CreateView): #Vistas basadas en clases
	#form = ProductoForm(request.POST or None, request.FILES)
	#form_class = ProductoForm
	model = Producto
	template_name = 'Producto/agregarProducto.html'
	fields = '__all__'
	success_url = reverse_lazy('producto:listar')
	success_message = 'Feriante agregado correctamente'

	'''
	
	REVISAR ESTE CODIGO CON NICO. NO ANDA!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	'''

	#return render(request, 'Producto/agregarProducto.html', context)

def AgregarProducto(request): #Vistas basadas en funciones
	form = ProductoForm(request.POST or None, request.FILES or None)

	if form.is_valid():
		ap = form.save(commit=False)
		ap.categoria = Categoria.objects.get(pk = request.POST.get('categoria'))
		ap.feriante = Feriante.objects.get(encargado = request.user.pk)
		ap.save()
		messages.success(request, 'Producto agregado correctamente') # este mensaje se tiene que modificar
		return redirect('producto:MisProductos')


	return render(request, 'Producto/agregarProducto.html', {'form': form, 'categoria': Categoria.objects.all(), 'feriantes': Feriante.objects.all()})

def MisProductos(request):
	currentFeriante = Feriante.objects.get(encargado = request.user)
	context = {}
	productos = Producto.objects.filter(feriante = currentFeriante)
	context['productos'] = productos

	return render(request,'Producto/misProductos.html', context)

class ModificarProducto(LoginRequiredMixin,UpdateView):
	model = Producto
	template_name = 'Producto/agregarProducto.html'
	fields = ['nombre', 'precio', 'stock', 'foto_producto', 'categoria', 'descripcion']
	success_url = reverse_lazy('producto:MisProductos')

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['categoria'] = Categoria.objects.all()
	
		return context

class EliminarProducto(LoginRequiredMixin,DeleteView):
	model = Producto
	template_name = 'Producto/eliminarProducto.html'
	success_url = reverse_lazy('producto:MisProductos')


class DetalleProducto(DetailView):
	model = Producto
	template_name = 'producto/detalle_producto.html'
	form_class = PedidoForm

	def get_context_data(self, **kwargs):
		context = super(DetalleProducto, self).get_context_data(**kwargs)
		categoria = Categoria.objects.filter(nombre = self.kwargs['categoria']).get()
		context_object_name = 'Sugerencia'
		list_sugerencia = Producto.objects.filter(categoria = categoria )
		
		cont = len(list_sugerencia)	
		iterador = 1
		cards=[]
		lista_productos=[]

		if self.request.user.is_authenticated:
			pedidos = Pedido.objects.filter(cliente = self.request.user).aggregate(Sum('cantidad'))
			context['Pedido'] = pedidos
		
		if cont > 3:
				
			for i in list_sugerencia:   
				cards.append(i) 
				if iterador % 3 == 0:
					lista_productos.append(cards) 
					#context['Sugerencia'] = cards
					print('esto es la lista de prod', lista_productos)
					cards=[]
					
					
				iterador += 1
					
			context['Sugerencia'] = lista_productos
			print('este es el contexto', context)
			return context
			
		else:
			
			return context
	
	def post(self,request,*args,**kwargs):
		form = self.form_class(request.POST)
		if form.is_valid():
			p = Producto.objects.get(pk = self.kwargs['pk'])
			try:
				pedido = Pedido.objects.get(cliente = request.user,producto = p)
				cant = request.POST.get('cantidad')
				total = Decimal(cant) * pedido.producto.precio
				suma = int(cant) + int(pedido.cantidad)
				if suma > 0:
					pedido.cantidad = int(cant) + int(pedido.cantidad)
					pedido.total = int(total) + int(pedido.total)
					pedido.save()
			except:
				res = form.save(commit = False)
				res.producto = p
				res.cliente = request.user
				cant = request.POST['cantidad']
				if int(cant) > 0:
					total = Decimal(cant) * p.precio
					res.total = total
					res.save()
			return HttpResponseRedirect('/producto/')
		return render(request,self.template_name, {'form':form})

feriacultiva/templates/Producto/MisProductos.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %} - Mis productos {% endblock titulo%}
{% block contenido %}  
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'css/productos.css' %}">
</head>

<section class="py-5">
	<div class="container"><!-- Container página principal -->
       <h2 class="my-4 text-center tit_principal">MIS PRODUCTOS</h1>
  		<div class="col-12" style="margin-bottom: 15px;">
  		<a class="btn" href="{% url 'producto:agregar' %}">Nuevo</a>
  		</div>
  		<div class="row">
  		
			

		{% if productos|length == 0 %}
           <label for=""  class=" mensaje ">No hay productos. </label>
          {% else%}
                {% for p in productos %}
                  <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                      <a href="{% url 'producto:Detalle' p.pk p.categoria.nombre %}" class="imagen" >
                        {% if p.foto_producto %}
                                <img class="img-prod" style="width: 100px; height: 150px;" 
                                src="{{p.foto_producto.url}}" alt="encontre">
                            {% else %}
                                <img class="img-prod" style="width: 80px; height: 150px;" 
                                src="" alt="No existe imagen" >
                        {% endif %}
                        </a>
                      <div class="card-body">
                        <h4 class="card-title">
                          <a class="ancla-titulo" href="{% url 'producto:Detalle' p.pk p.categoria.nombre %}" class="imagen"> {{p.nombre}} </a>
                        </h4>
                        <h5 class="prod text-center"> ${{p.precio}} </h5>
                   
                      {% if p.stock > 0 %}
                        <p class="card-text"> Stock: {{p.stock}} </p>
                      {% else %}
                        <p class="card-text"> No hay stock disponible </p>
                      {% endif %}

                      </div>
                      <div class="card-footer text-center" style="background-color: #fff;">
                        <!-- Cambiar el diseño del boton en caso de que no haya mas en stock -->
                       <a style="color: #71a95a;" href="{% url 'producto:modificar' p.pk %}">Modificar</a> |

                       <!-- Botón en HTML (lanza el modal en Bootstrap) -->
                       <a style="color: #da2d2d;" href="#victorModal{{p.pk}}" data-toggle="modal">Eliminar</a>
                                   <!-- Modal / Ventana / Overlay en HTML -->
				        <div id="victorModal{{p.pk}}" class="modal fade">
				           <div class="modal-dialog">
				              	<div class="modal-content">
					                <div class="modal-header">
					                  <h4 class="modal-title">¿Estás seguro?</h4>
					                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>   
					                </div>
					              	<div class="modal-body">
					               		<p>¿Seguro que quieres borrar este elemento?</p>
					                	<p class="text-warning">
					                		<small>Si lo borras, no podrás recuperarlo.</small></p>
					                </div>
					                <div class="modal-footer">
					                	<button type="button" class="btn" data-dismiss="modal">Cancelar</button>
					                                    
					                	<form action="{% url 'producto:eliminar' p.pk %}" method="POST">
					                	{% csrf_token %}
					                		<button class="btn" type="submit" href="">Eliminar</button>
					                	</form>
					              	</div>
				            	</div>
				          	</div> 
                      	</div>
                      </div>


                    </div>
                  </div>
                {% endfor %}
                {% endif %}
          


		</div> <!-- /.row contenido principal-->
	</div>    <!-- /.container -->    
</section>
{% endblock contenido%}

feriacultiva/templates/Producto/agregarProducto.html
{% extends 'base.html' %}
{% load static %}



{% block titulo %} Productos {% endblock titulo%}


{% block contenido %}  
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/altaProd.css' %}">
</head>

<!-- Contenido de la pagina -->
<section class="py-5">
  <!-- titulo y subtitulo de la pagina -->
  <div class="container">
		    
		
	<div style="margin-top: 35px;">  


		{% if object %}
		<h2 class="my-4 titulo text-center">MODIFICAR PRODUCTO</h2>
			<form action="" method="POST" class="titulo"> {% csrf_token %}
                <!-- <label for="encargado">Encargado: </label>
                <input type="text" name="encargado" id="encargado" value="{{feria.encargado.username}}"><br> -->
                <div class="row">
                    <div class="col-md-6 text-center w-25">
                        <div class="col-12">
                            <i class="fa fa-camera"></i> <label>Foto:</label>
                        </div>
                        <div class="fotoproducto">
                        {% if object.foto_producto %}
                        <img class="" src="{{object.foto_producto.url}}" alt="foto">
                        {% else %}
                        <img src="" alt="no existe">
                        {% endif %}
                        </div> 
                        <input type="file" name="foto_producto" value="{{object.foto_producto.url}}">
                    </div>

                    <div class="col-md-6" style="margin-top: 20px;">
                    	<div class="items">
                    		<label>Producto</label>
                            <input type="text" name="nombre" id="nombre" value="{{object.nombre}}">
                        </div>
                        <div class="items">
                            <label>Precio</label> 
		                    <input  type="number" name="precio" id="precio" value="{{object.precio}}">
		                </div>
		                <div class="items">
                            <label>Stock</label> 
		                    <input  type="number" name="stock" id="stock" value="{{object.stock}}">
		                </div>
		                <div class="items">
                           <label>Seleccionar categoria</label>
		                        <select name="categoria">
									{% for c in categoria %}
										<option value="{{c.pk}}">{{ c }}</option>
									{% endfor %}
								</select>
		                </div>
		                <div class="items">
                            <label>Descripción</label> 
		                    <input  type="text" name="descripcion" id="descripcion" value="{{object.descripcion}}">
		                </div>
                       
                    </div>
                </div>
                    <div class="col-12 text-center" style="margin-top: 30px;">
                        <button class="btn alta-prod" type="submit">Guardar cambios</button>
                    </div>
                </form>
<!-- 

			<form autocomplete="off" method="POST"  enctype="multipart/form-data">{% csrf_token %}
				{{form.as_p}}
				<button type="submit">save</button>
				
			</form> -->
		{% else %}
<!--formulario -->
		<h2 class="my-4 titulo text-center">NUEVO PRODUCTO</h2>
		<div class="container h-100 " style="background-color: #f5f5f5;padding-top: 15px; padding-bottom: 15px;" >

			<div  class="row justify-content-center align-items-center">
				
			{% for x in messages %}
				            <div class="alert alert-success">
				                {{x}}
				            </div>
		            {% endfor %}
		     <div class="col col-sm-6 col-md-6 col-lg-6 ">
		       <form autocomplete="off" method="POST"  enctype="multipart/form-data"  >
				            {% csrf_token %}
				            {% if form.errors %}
							<div class="alert" style="background-color: red;">
						      {{form.errors}}
						    </div>
							{% endif %}

		                
		                    <div class="form-group">
		                        <label  class="control-label">Nombre del producto</label> 
		                        <input  type="text" maxlength="35" class="form-control" placeholder="Ingrese el nombre del producto" name="nombre">
		                    </div>
		             
		            
		            
		                    <div class="form-group">
		                        <label  for="inputApellido">Precio</label> 
		                        <input  type="number" class="form-control" placeholder="Ingrese el precio" name="precio">
		                    </div>
		               
		                
		                    <div class="form-group">
		                        <label for="inputApellido">Stock</label> 
		                        <input type="number" class="form-control" placeholder="Ingrese el stock" name="stock">
		                    </div>
		               	
							<div class="form-group">
		                        <label >Descripción</label>
		                        <input type="text" maxlength="100" class="form-control" placeholder="Ingrese una descripción" name="descripcion">
		                        <small style="color: #2c5d63;">Cantidad máxima: 100 caracteres.</small>
		                        <!-- <input type="submit" value="Enviar datos">-->
		                    </div>
						
		                    <div class="form-group">
		                        <label >Imagen del producto</label>
		                        <img src=""> 
		                        <input type="file" name="foto_producto">
		                        <!-- <input type="submit" value="Enviar datos">-->
		                    </div>
		              
		           
		              
		                
		                    <div class="form-group">
		                    	<label>Seleccionar categoria</label>
		                        <select name="categoria">
									{% for c in categoria %}
										<option value="{{ c.pk }}">{{ c }}</option>
									{% endfor %}
								</select>
		                    </div>
		              



		            <div class="row justify-content-center align-items-center">
		            	<button class="btn alta-prod" type="submit"href="{% url 'producto:listar' %}">Cancelar</button>
		            	<button class="btn alta-prod" type="submit">Guardar</button>
		            </div>
		
				 	{% if object %}
				 		<div>
				 			<a type="submit" href="{% url 'producto:eliminar' object.pk %}" class="btn btn-danger">Eliminar</a>
				 		</div>
				 	
				 	{% endif %}

				 	</div>
		        </form> 
 				</div>
		      </div>
		   </div><!--fin container form-->
		   	{% endif %}

		</div><!--fin row-->
  
  </div>  <!-- /fin container -->     
</section>
{% endblock contenido%}

feriacultiva/templates/Producto/eliminarProducto.html
{% extends 'base.html' %}

{% block contenido %}

	<form method="POST">
		{% csrf_token %}
		<div class="alert alert-danger mt-5 ml-3 mr-3" role="alert">Estas seguro que quieres eliminar el producto {{ object.nombre }}?</div>
		<button class="btn btn-danger ml-3" type="submit">Si</button>
	</form>
{% endblock contenido %}

feriacultiva/templates/Producto/listar.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %} Productos {% endblock titulo%}
{% block contenido %}  
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'css/productos.css' %}">

 
</head>
<header class="masthead" style="background-image: url({% static 'img/nuevo1.png' %})">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12 text-center">
      <h1 class="my-1 titulo-h1 ">
         Productos
       </h1>
        <p class="lead"></p>
      </div>
    </div>
  </div>
</header>






<section class="py-5"><!-- Page Content -->




  <div class="container"><!-- Container página principal -->

   

<div class="row">    <!-- row página principal -->

 <!-- USAR ESTE FILTRO X EL MOMENTO -->
<div class="col-lg-3" style="padding-top: 0px" > 

 <!--   <div>
          {% if user.es_empresa %}
            <button class="btn float-right" type="button"  >
            <a href="{% url 'producto:agregar' %}">
                Nuevo</a>
            </button>
            <button><a href="{% url 'feriante:MisProductos' %}">Mis Productos</a></button>
          {% endif %}
    </div> -->

  <div class="row" style="padding-top: 70px;">
      
          <div id="custom-search-input">
            <form method="get">
                <div class="input-group">
                    <input type="text" name="buscador" class="search-query form-control" placeholder="Buscar" />
                    <span class="input-group-btn">
                        <button type="submit" >
                            <span class="fa fa-search"></span>
                        </button>
                    </span>
                </div>
              </form>
          </div>
  
  </div>



    
  

        <div class="list-group filtro">
          <small  class="filtro-m"> Seleccionar y luego click en el icono filtrar. </small>
          <form>
              <select name="Categoria" class="selector">
                  <option class="op1" value="0">Todos</option>
                      {% for r in filtro %}
                  <option class="op2" value="{{r.pk}}">{{r.nombre}}</option>
                      {% endfor %}
              </select>
              <button class=" filtrar-boton "  type="submit">
                <span class="fas fa-filter" style="color:#696464;"> </span>
              </button>       
          </form>
        </div>



  </div>
   

    <!-- <div class="row"> PROXIMAMENTE XD
      <div class="col-lg-3">
        <h3 class="my-5">CATEGORÍAS</h3>
        <div class="list-group">
          <a href="#" class="list-group-item">Category 1</a>
          <a href="#" class="list-group-item">Category 2</a>
          <a href="#" class="list-group-item">Category 3</a>
        </div>
      </div> -->
      <!-- /.col-lg-3 -->
     
      <div class="col-lg-9 "  >
        <div class="row">

          {% if object_list|length == 0 %}
           <label for=""  class=" mensaje ">No hay productos. </label>
          {% else%}
                {% for p in object_list %}
                  <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                      <a href="{% url 'producto:Detalle' p.pk p.categoria.nombre %}" class="imagen" >
                        {% if p.foto_producto %}
                                <img class="img-prod" style="width: 100px; height: 150px;" 
                                src="{{p.foto_producto.url}}" alt="encontre">
                            {% else %}
                                <img class="img-prod" style="width: 80px; height: 150px;" 
                                src="" alt="No existe imagen" >
                        {% endif %}
                        </a>
                      <div class="card-body">
                        <h4 class="card-title">
                          <a class="ancla-titulo" href="{% url 'producto:Detalle' p.pk p.categoria.nombre %}" class="imagen"> {{p.nombre}} </a>
                        </h4>
                        <h5 class="prod"> ${{p.precio}} </h5>
                   
                      {% if p.stock > 0 %}
                        <p class="card-text"> Stock disponible </p>
                      {% else %}
                        <p class="card-text"> No hay stock disponible </p>
                      {% endif %}

                      </div>
                      <!-- <div class="card-footer " style="background-color: #fff;">
                        
                        
                      {% if p.stock > 0 %}

                     <form  action="" method="post" enctype="multipart/form-data" style=" text-align: center; "  >{% csrf_token %}
  
                            <input type="number" name="cantidad" id="cantidad" placeholder="1" value="1">
                            {% if user.is_authenticated %}

                            <button class="reservar" type="submit" value="{{p.pk}}" name="Confirmar" style=" padding-top: 5px;"><i class="fas fa-cart-plus"  style="font-size: 25px; color: #283739; "></i></button>
                            {% endif %}
                     </form>
                          {% else %}
                          <a href="#">No disponible</a>
                        {% endif %}
                      </div> -->


                    </div>
                  </div>
                {% endfor %}
                  </div> <!-- /.row col-lg-9 -->

         <!--/paginación-->
        <div class="col-lg-2 mx-auto">
            <nav aria-label="Page navigation example">
              <ul class="pagination">
                {% if page_obj.has_previous %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{ page_obj.previous_page_number}}" aria-label="Previous">
                          <span aria-hidden="true">&laquo;</span>
                          <span class="sr-only">Previous</span>
                      </a>
                  </li>
                {% endif %}

                {% for page in page_range %}
                  <li {% if page == page_obj.number %} class="page-item" {% endif %}>
                  <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                  </li>
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.next_page_number}}" aria-label="Next">
                    
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                  </a>
                </li>
                {% endif %}

              </ul>
            </nav>
        </div>
      </div><!-- /.col-lg-9 -->
              {% endif %}

      

    </div> <!-- /.row contenido principal-->
   
        
  </div>    <!-- /.container -->    
</section>
{% endblock contenido%}